### ISSUE TITLE
Fluent UI Nav

### ISSUE THREAD

**Issue by Sagensagen** [sydsutton/FS.FluentUI#8]
## Fluent UI  React NAV
[Nav](https://react.fluentui.dev/?path=/docs/preview-components-nav--nav-drawer-default)
Will Nav be added to the project in the nearest future? It is still in preview but would love to use this component as it looks very clean.

**Comment by sydsutton** [comment]
I've decided to wait until the preview components are released as `Stable` before I add them to the project. It minimizes the number of JS packages we need to use. Plus, it's nice not constantly deploying breaking changes because they changed the API for a preview component. 
They don't have an ETA for when Nav will be released as stable, unfortunately. Hopefully it's soon!

**Comment by sydsutton** [comment]
@Sagensagen FYI here's a `Component RoadMap` for V9s progress. https://github.com/orgs/microsoft/projects/786/views/1

**Comment by Sagensagen** [comment]
Perfect!

**Comment by shayanhabibi** [comment]
Looks like they're aiming to complete it by EoY; already looks like it's on it's way to final revisions since the docs don't have the proviser that the API is unstable etc

Since there's some new elements such as v8tov9 that will change or be introduced, would it be fair to assume you would consider a major release bump?

In this case, would you also consider updating the library/testing grounds to .net 8 or .net 9 minimum?

**Comment by sydsutton** [comment]
@shayanhabibi i wouldn't hold your breath, I've been waiting for like 7 months for a BasicList component. By "new elements" do you mean new components? If so, it'll likely be a minor bump. I can look into migrating to .NET8 soon, though.

**Comment by sydsutton** [comment]
@shayanhabibi you can be assured, though, that once they release a stable version of Nav, I'll have a new version of FS.FluentUI with Nav out within 36 hours.

**Comment by shayanhabibi** [comment]
> @shayanhabibi i wouldn't hold your breath, I've been waiting for like 7 months for a BasicList component. By "new elements" do you mean new components? If so, it'll likely be a minor bump. I can look into migrating to .NET8 soon, though.

Well I suppose it would be good to have a solid version which introduces stack into the fold and a more finalised api that isn't concerned with backwards compatibility that contributors can help document. Your comment is fair enough though hahaha.

I was looking into doing a pull for the preview version of the navbar (before seeing this issue) but noticed it was on .NET7 when I was trying to build the tests.

Not an issue, I will naturally get the .net7 sdk if it is preferential to maintain the backwards compatibility in the f# language spec (which is mostly what would be useful in upgrading for).

I'll hopefully be able to provide contribution as I learn the technology better from your examples and from tinkering.

**Comment by shayanhabibi** [comment]
I've started perusing the discussions and noticed it was already addressed in #3

Seems i've got it backwards! Stack was a v8 thing from what I understand?

**Comment by sydsutton** [comment]
`Fui.stack` is available through FS.FluentUI.V8toV9. I made a separate package just for stack because of how helpful I find it. You just need to also download the `@fluentui/react-migration-v8-v9` NPM package along with it. And yes, it was a V8 thing that I wanted to bring into the V9 space. I'll definitely look into updating to .NET8 though.

**Comment by Sagensagen** [comment]
I ended with implementing the `Nav` component through the preview package in JSX for now. Works like a charm, but not the prettiest as the rest of the application is 99% Fui. Hopefully the release won't break too much.

**Comment by sydsutton** [comment]
@Sagensagen @shayanhabibi OK, I'll work on a UNSTABLE version of Nav. I'll keep you updated.

**Comment by sydsutton** [comment]
@Sagensagen @shayanhabibi  Ok, version 1.17.0 that was just pushed has unstable Nav components in it. Those components are likely to change, so please use caution when using in production. Here's the wiki page for it: https://github.com/sydsutton/FS.FluentUI/wiki/Nav-(unstable)

**Comment by Sagensagen** [comment]
You sir deserve more stars. This will indeed be used in production soon and follow closely for issues that might arise.

**Comment by sydsutton** [comment]
Hey @shayanhabibi @Sagensagen they just pushed back the projected date for a stable Nav by 2 months to be the end of March.  -___-

**Comment by Sagensagen** [comment]
Preview does the job in the meantime. No worries 🙌
